Repository go-vela/vela-artifactory, pull requests merged in 2020-01, with the labels that each got.

#4 refactor: move code to cmd directory
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  Makefile
  cmd/vela-artifactory/main.go
  cmd/vela-artifactory/main_test.go
  cmd/vela-artifactory/plugin.go
  cmd/vela-artifactory/plugin_test.go
  cmd/vela-artifactory/testdata/mock.go
  cmd/vela-artifactory/testdata/upload-args.json
Labels: enhancement

#5 feat: add copy struct for plugin
  .gitignore
  cmd/vela-artifactory/copy.go
  cmd/vela-artifactory/copy_test.go
Labels: feature

#6 feat: add delete struct for plugin
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/delete_test.go
Labels: feature

#7 feat: add prop and setprop structs for plugin
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/prop_test.go
Labels: feature

#8 feat: add upload struct for plugin
  cmd/vela-artifactory/upload.go
  cmd/vela-artifactory/upload_test.go
Labels: feature

#9 chore: add copyright notice to plugin files
  cmd/vela-artifactory/copy.go
  cmd/vela-artifactory/copy_test.go
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/delete_test.go
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/prop_test.go
  cmd/vela-artifactory/upload.go
  cmd/vela-artifactory/upload_test.go
Labels: enhancement

#10 feat: add certs from alpine
  Dockerfile
Labels: feature

#11 feat: add config struct for plugin
  cmd/vela-artifactory/config.go
  cmd/vela-artifactory/config_test.go
Labels: feature

#13 feat: add plugin struct
  cmd/vela-artifactory/plugin.go
  cmd/vela-artifactory/plugin_test.go
Labels: feature

#14 refactor: add extra information for plugin
  cmd/vela-artifactory/config.go
  cmd/vela-artifactory/config_test.go
  cmd/vela-artifactory/copy.go
  cmd/vela-artifactory/copy_test.go
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/main.go
  cmd/vela-artifactory/plugin.go
  cmd/vela-artifactory/plugin_test.go
  cmd/vela-artifactory/prop.go
Labels: enhancement

#15 feat: enable loading config from env file
  cmd/vela-artifactory/main.go
  go.mod
  go.sum
Labels: feature

#16 refactor: validate action specific configuration
  cmd/vela-artifactory/copy.go
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/plugin.go
  cmd/vela-artifactory/plugin_test.go
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/upload.go
Labels: enhancement

#17 feat: add new method for config
  cmd/vela-artifactory/config.go
  cmd/vela-artifactory/config_test.go
Labels: feature

#18 feat: add exec method for copy
  cmd/vela-artifactory/copy.go
  cmd/vela-artifactory/copy_test.go
Labels: feature

#19 feat: add exec method for delete
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/delete_test.go
Labels: feature

#20 feat: add exec method for setprop
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/prop_test.go
Labels: feature

#21 feat: add exec method for upload
  cmd/vela-artifactory/upload.go
  cmd/vela-artifactory/upload_test.go
Labels: feature

#22 refactor: remove dead code
  artifactory/artifactory.go
  artifactory/artifactory_test.go
  artifactory/config.go
  artifactory/config_test.go
  artifactory/copy.go
  artifactory/copy_test.go
  artifactory/delete.go
  artifactory/delete_test.go
  artifactory/props.go
  artifactory/props_test.go
  artifactory/search.go
  artifactory/upload.go
  artifactory/upload_test.go
  go.mod
  go.sum
Labels: enhancement

#23 feat: add exec method for plugin
  cmd/vela-artifactory/plugin.go
  cmd/vela-artifactory/plugin_test.go
Labels: feature

#24 docs: add plugin usage docs
  .github/README.md
  DOCS.md
Labels: enhancement

#25 chore: update copyright for 2020
  .github/README.md
  Dockerfile
  Makefile
  cmd/vela-artifactory/config.go
  cmd/vela-artifactory/config_test.go
  cmd/vela-artifactory/copy.go
  cmd/vela-artifactory/copy_test.go
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/delete_test.go
  cmd/vela-artifactory/main.go
  cmd/vela-artifactory/plugin.go
  cmd/vela-artifactory/plugin_test.go
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/prop_test.go
  cmd/vela-artifactory/testdata/mock.go
  cmd/vela-artifactory/upload.go
  cmd/vela-artifactory/upload_test.go
Labels: enhancement

#26 feat: enable dry_run mode for plugin
  cmd/vela-artifactory/config.go
  cmd/vela-artifactory/config_test.go
  cmd/vela-artifactory/copy_test.go
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/delete_test.go
  cmd/vela-artifactory/main.go
  cmd/vela-artifactory/plugin_test.go
  cmd/vela-artifactory/prop_test.go
  cmd/vela-artifactory/upload.go
  cmd/vela-artifactory/upload_test.go
Labels: feature

#27 feat: add plugin template
  .vela/template.yml
Labels: feature

#28 feat: add logic for setting properties
  cmd/vela-artifactory/main.go
  cmd/vela-artifactory/plugin_test.go
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/prop_test.go
  go.mod
  go.sum
Labels: feature

#29 docs: add comments for code
  cmd/vela-artifactory/config.go
  cmd/vela-artifactory/copy.go
  cmd/vela-artifactory/delete.go
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/upload.go
Labels: enhancement

#30 chore: add debug and trace logs
  cmd/vela-artifactory/config.go
  cmd/vela-artifactory/prop.go
Labels: enhancement

#31 fix(set-prop): switch from generic to string flag
  cmd/vela-artifactory/main.go
  cmd/vela-artifactory/plugin_test.go
  cmd/vela-artifactory/prop.go
  cmd/vela-artifactory/prop_test.go
  go.mod
Labels: bug

#32 fix: update syntax for makefile
  Makefile
Labels: bug

#33 chore: use full apache license
  LICENSE
Labels: enhancement

#34 improvement: add log entry with metadata
  cmd/vela-artifactory/main.go
Labels: enhancement

#35 feat: add docker promotion functionality
  cmd/vela-artifactory/docker_promote.go
  cmd/vela-artifactory/docker_promote_test.go
  cmd/vela-artifactory/main.go
  cmd/vela-artifactory/plugin.go
  cmd/vela-artifactory/plugin_test.go
  go.mod
  go.sum
Labels: feature
