Repository go-vela/vela-artifactory, pull requests merged in 2020-07, with the labels that each got.

#49 ci: refactor Makefile. improve linter setup. upgrade deps.
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .golangci.yml
  Makefile
  codecov.yml
  go.mod
  go.sum
Labels: dependencies, enhancement

#50 chore: add docker-promote to documentation
  DOCS.md
Labels: enhancement

#51 feat(config): add file path option for reading values
  DOCS.md
  cmd/vela-artifactory/main.go
Labels: feature
